#!/usr/bin/env python3
"""
Authentication module for the API.
"""
from flask import request
from typing import List, TypeVar


class Auth:
    """
    Template class for implementing authentication systems.
    """
    def require_auth(self, path: str, excluded_paths: List[str]) -> bool:
        """
        Determines if authentication is required for a given path.

        Args:
            path (str): The path to check
            excluded_paths (List[str]): List of paths that don't require authentication

        Returns:
            bool: False for now as per requirements
        """
        return False

    def authorization_header(self, request=None) -> str:
        """
        Gets the authorization header from the request.

        Args:
            request: Flask request object

        Returns:
            str: None for now as per requirements
        """
        return None

    def current_user(self, request=None) -> TypeVar('User'):
        """
        Gets the current user from the request.

        Args:
            request: Flask request object

        Returns:
            User: None for now as per requirements
        """
        return None
